---
name: pypi-publish
description: Upload Python distribution packages to PyPI
inputs:
  user:
    description: PyPI user
    required: false
    default: __token__
  password:
    description: Password for your PyPI user or an access token
    required: true
  repository_url:
    description: The repository URL to use
    required: false
  packages-dir:
    description: The target directory for distribution
    required: false
    default: dist
branding:
  color: yellow
  icon: upload-cloud
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.user }}
  - ${{ inputs.password }}
  - ${{ inputs.repository_url }}
  - ${{ inputs.packages-dir }}
